name: event_bus
version: 2.0.0
author: Sumit Tiware
description: A simple Event Bus using Dart Streams for decoupling applications
repository: https://github.com/marcojakob/dart-event-bus
homepage: https://code.makery.ch/library/dart-event-bus/
environment:
  sdk: ">=3.0.0<=3.10.5"
dependencies:
  flutter:
    sdk: flutter
# dev_dependencies:
  # build_runner: ^1.2.5
  # build_web_compilers: ^2.16.4
  # build_test: ^1.3.7
  # logging: ^1.0.0
  # test: ^1.5.0
